# @author Ayaan

name: Build Debug ğŸ—ï¸

on :
  push :
    branches:
      - ci_cd

jobs :
  build :
    runs-on :  ubuntu-latest
    steps:
      -  uses :  actions/checkout@v2
      -  name :  set up JDK 11
         uses :  actions/setup-java@v1
         with :
            java-version :  11
            distribution :  'temurin'
            cache :  gradle

      -  name :  Make gradlew executable
         run :  chmod +x ./gradlew

      -  name :  Build Debug APK
         run :  ./gradlew :app:assembleDebug :app:bundleDebug

      -  name :  Upload APK
         uses :  actions/upload-artifact@v2
         with :
            name :  apk
            path :  app/build/outputs/apk/debug/app-debug.apk

      -  name :  Upload AAB
         uses : actions/upload-artifact@v2
         with :
            name :  aab
            path :  app/build/outputs/bundle/debug/app-debug.aab
